use feature="raw" on the hashbrown dependency
Summary:
D53506886 introduced [an issue](https://fburl.com/sandcastle/kphopyhi) in buck2/allocative but that got incorrectly flagged as a warning when the base revision retry failed with a different reason. Recent runs of `buck2-allocative-oss` job failed with the issue, https://fburl.com/scuba/sandcastle/6n14m316.

Per dtolnay's suggestion, adding `feature="raw"` on the hashbrown dependency as it looks like the other Cargo files are configured the same way.

This issue is found because [our test](https://www.internalfb.com/intern/test/562950049620409/) that depends on rust-toolchain started failing with the same error.

```
error[E0603]: module `raw` is private
  --> allocative/src/impls/hashbrown.rs:14:16
   |
14 | use hashbrown::raw::RawTable;
   |                ^^^ private module
   |
note: the module `raw` is defined here
  --> /var/twsvcscm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.3/src/lib.rs:76:1
   |
76 | mod raw;
   | ^^^^^^^
```

Reviewed By: dtolnay

Differential Revision: D53723423

fbshipit-source-id: c2a61d2be7c2dcaac7b0e99aa179c0008b8ef3cf